using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Drawing;
using System.Threading;
namespace DISCO
{
    class colors
    {
        private bool run = true;
        public bool Run
        {
            set { run = value; }
            get { return run; }
        }

        public void regular()
        {
            do
            {
                Form1.ActiveForm.BackColor = Color.Red;
                Thread.Sleep(600);
                Form1.ActiveForm.BackColor = Color.Yellow;
                Thread.Sleep(600);
                Form1.ActiveForm.BackColor = Color.Blue;
                Thread.Sleep(600);
                Form1.ActiveForm.BackColor = Color.Green;
                Thread.Sleep(600);
                Form1.ActiveForm.BackColor = Color.Purple;
                Thread.Sleep(600);
            } while (Run);
        }
        public void allcolors()
        {
            do
            {
                Form1.ActiveForm.BackColor = Color.AliceBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.AntiqueWhite;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Aqua;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Aquamarine;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Azure;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Beige;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Bisque;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Black;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.BlanchedAlmond;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Blue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.BlueViolet;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Brown;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.BurlyWood;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.CadetBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Chartreuse;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Chocolate;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Coral;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.CornflowerBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Cornsilk;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Crimson;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Cyan;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkCyan;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkGoldenrod;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkKhaki;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkMagenta;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkOliveGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkOrange;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkOrchid;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkRed;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkSalmon;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkSeaGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkSlateBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkSlateGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkTurquoise;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DarkViolet;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DeepPink;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DeepSkyBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DimGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.DodgerBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Firebrick;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.FloralWhite;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.ForestGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Fuchsia;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Gainsboro;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.GhostWhite;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Gold;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Goldenrod;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Gray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Green;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.GreenYellow;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Honeydew;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.HotPink;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.IndianRed;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Indigo;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Ivory;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Khaki;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Lavender;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LavenderBlush;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LawnGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LemonChiffon;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightCoral;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightCyan;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightGoldenrodYellow;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightPink;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightSalmon;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightSeaGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightSkyBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightSlateGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightSteelBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LightYellow;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Lime;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.LimeGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Linen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Magenta;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Maroon;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumAquamarine;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumOrchid;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumPurple;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumSeaGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumSlateBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumSpringGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumTurquoise;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MediumVioletRed;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MidnightBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MintCream;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.MistyRose;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Moccasin;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.NavajoWhite;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Navy;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.OldLace;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Olive;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.OliveDrab;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Orange;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.OrangeRed;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Orchid;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PaleGoldenrod;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PaleGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PaleTurquoise;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PaleVioletRed;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PapayaWhip;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PeachPuff;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Peru;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Pink;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Plum;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.PowderBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Purple;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Red;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.RosyBrown;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.RoyalBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SaddleBrown;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Salmon;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SandyBrown;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SeaGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SeaShell;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Sienna;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Silver;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SkyBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SlateBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SlateGray;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Snow;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SpringGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.SteelBlue;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Tan;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Teal;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Thistle;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Tomato;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Transparent;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Turquoise;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Violet;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Wheat;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.White;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.WhiteSmoke;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Yellow;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.YellowGreen;
                Thread.Sleep(500);
                Form1.ActiveForm.BackColor = Color.Purple;
                Thread.Sleep(500);
            } while (Run);
        }

       
    }
}
